services:
  # Web Application, Backend API & Telegram Bot (JavaScript)
  - type: web
    name: creator-web-app
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
